vagrantfile:
    vm:
        provider:
            local:
                machines:
                    machine1:
                        id: wp-puphpet
                        hostname: local.wp-puphpet.io
                        network:
                            private_network: 172.23.0.55
                        cpus: '2'
        synced_folder:
            folder1:
                source: ./
                target: /var/www/wordpress
apache:
    vhosts:
        vhost1:
            servername: wp-puphpet.io
            serveraliases:
            - local.wp-puphpet.io
            - dev.wp-puphpet.com
            docroot: /var/www/wordpress/html
            directories:
                php_html:
                    path: /var/www/wordpress/html
                php_php:
                    www_root: /var/www/wordpress/html
